# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-Babel
version:      v0.0.3
version_from: lib/GPS/Babel.pm
installdirs:  site
requires:
    Class::Std:                    0
    File::Which:                   0
    Geo::Gpx:                      0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
