# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-Babel
version:      v0.0.2
version_from: lib/GPS/Babel.pm
installdirs:  site
requires:
    Carp:                          0
    File::Which:                   0
    HTML::Entities:                0
    IO::Pipe:                      0
    Test::More:                    0
    Time::Local:                   0
    version:                       0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
